services:
  - type: web
    name: ppal-backend
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
